const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const screens=$$('.screen'); const hud=$('#hud'); const musicA=$('#musicA'), musicB=$('#musicB');
let level=0, muted=false, volume=.18, activeMusic=musicA;
const levels=[
 {name:'Memória',icon:'🧠',title:'Jogo da memória',text:'Encontre todos os pares. Toque em duas cartas por vez e memorize onde cada símbolo está.',game:memoryGame},
 {name:'Alvo rápido',icon:'🎯',title:'Alvo rápido',text:'Acerte 10 alvos antes que o tempo termine. O alvo muda de lugar após cada toque.',game:targetGame},
 {name:'Sequência',icon:'🎨',title:'Sequência de cores',text:'Observe a sequência iluminada e repita na mesma ordem. Complete cinco rodadas.',game:simonGame},
 {name:'Labirinto',icon:'🧭',title:'Labirinto',text:'Leve o explorador até o troféu usando os controles. Os blocos escuros são paredes.',game:mazeGame},
 {name:'Ordem',icon:'🔢',title:'Ordem numérica',text:'Toque nos números do menor para o maior. Eles estão embaralhados e você deve completar sem errar.',game:orderGame},
 {name:'Reflexo',icon:'⚡',title:'Teste de reflexo',text:'Espere o painel ficar verde e toque imediatamente. Não toque antes da mudança.',game:timingGame}
];
function show(id){screens.forEach(x=>x.classList.remove('active')); $('#'+id).classList.add('active'); scrollTo({top:0,behavior:'smooth'})}
function updateHud(){const L=levels[level]; $('#levelLabel').textContent=`Fase ${level+1}/${levels.length}`;$('#levelName').textContent=L.name;$('#progressBar').style.width=`${level/levels.length*100}%`}
function briefing(){const L=levels[level];updateHud();$('#briefIcon').textContent=L.icon;$('#briefStage').textContent=`FASE ${level+1}`;$('#briefTitle').textContent=L.title;$('#briefText').textContent=L.text;show('briefing')}
function complete(msg='A próxima etapa foi desbloqueada.'){$('#transitionTitle').textContent=level===levels.length-1?'Todos os jogos concluídos!':'Muito bem!';$('#transitionText').textContent=msg;show('transition');navigator.vibrate?.(60)}
$('#readyCheck').addEventListener('change',e=>$('#startBtn').disabled=!e.target.checked);
$('#startBtn').onclick=async()=>{hud.classList.remove('hidden');musicA.volume=volume;musicB.volume=volume;try{await musicA.play();$('#soundBtn').textContent='🔊'}catch(err){console.warn('O navegador bloqueou ou não encontrou o áudio:',err);$('#soundBtn').textContent='🔇'}briefing()};
$('#playBtn').onclick=()=>{show('game');$('#statusText').textContent='';$('#gameArea').innerHTML='';levels[level].game()};
$('#nextBtn').onclick=()=>{level++;if(level<levels.length)briefing();else{hud.classList.add('hidden');crossfade(musicB);show('reward')}};
$('#openRewardBtn').onclick=runReward;$('#restartBtn').onclick=()=>location.reload();
$('#soundBtn').onclick=()=>$('#volumePop').classList.toggle('hidden');$('#volumeSlider').oninput=e=>{volume=e.target.value/100;musicA.volume=muted?0:volume;musicB.volume=muted?0:volume};$('#muteBtn').onclick=()=>{muted=!muted;musicA.volume=muted?0:volume;musicB.volume=muted?0:volume;$('#soundBtn').textContent=muted?'🔇':'🔊';$('#muteBtn').textContent=muted?'Ativar':'Silenciar'};
function crossfade(next){if(next===activeMusic)return;next.volume=0;next.play().catch(()=>{});let i=0;const t=setInterval(()=>{i++;activeMusic.volume=Math.max(0,volume*(1-i/20));next.volume=muted?0:volume*(i/20);if(i>=20){clearInterval(t);activeMusic.pause();activeMusic=next}},75)}
function shuffle(a){return a.map(v=>[Math.random(),v]).sort((a,b)=>a[0]-b[0]).map(x=>x[1])}
function memoryGame(){const symbols=shuffle(['🌙','⭐','🎵','🎮','🌈','🍀','🎨','🚀'].flatMap(x=>[x,x]));let open=[],matched=0,lock=false;const grid=document.createElement('div');grid.className='memory-grid';symbols.forEach((s,i)=>{const b=document.createElement('button');b.className='memory-card';b.innerHTML=`<span class="memory-question">?</span><span class="memory-symbol">${s}</span>`;b.onclick=()=>{if(lock||b.classList.contains('open')||b.classList.contains('matched'))return;b.classList.add('open');open.push({b,s});if(open.length===2){lock=true;setTimeout(()=>{if(open[0].s===open[1].s){open.forEach(x=>x.b.classList.add('matched'));matched+=2;if(matched===symbols.length)setTimeout(()=>complete('Sua memória venceu a primeira fase.'),500)}else open.forEach(x=>x.b.classList.remove('open'));open=[];lock=false},650)}};grid.append(b)});$('#gameArea').append(grid)}
function targetGame(){let score=0,time=20,timer;$('#gameArea').innerHTML=`<div class="score-row"><span>Acertos: <b id="score">0/10</b></span><span>Tempo: <b id="time">20</b>s</span></div><div class="target-board" id="board"></div>`;const board=$('#board');function spawn(){board.innerHTML='';const t=document.createElement('button');t.className='target';const maxX=Math.max(0,board.clientWidth-72),maxY=Math.max(0,board.clientHeight-72);t.style.left=Math.random()*maxX+'px';t.style.top=Math.random()*maxY+'px';t.onclick=()=>{score++;$('#score').textContent=score+'/10';navigator.vibrate?.(20);if(score>=10){clearInterval(timer);complete('Você acertou todos os alvos a tempo.')}else spawn()};board.append(t)}spawn();timer=setInterval(()=>{time--;$('#time').textContent=time;if(time<=0){clearInterval(timer);$('#statusText').textContent='O tempo acabou. Toque para tentar novamente.';board.innerHTML='<button class="primary">Tentar novamente</button>';board.firstChild.onclick=targetGame}},1000)}
function simonGame(){let seq=[],input=[],round=0,busy=true;$('#gameArea').innerHTML=`<div class="simon-info" id="simonInfo">Prepare-se...</div><div class="simon">${[0,1,2,3].map(i=>`<button class="simon-btn" data-i="${i}"></button>`).join('')}</div>`;const btns=$$('.simon-btn');btns.forEach(b=>b.onclick=()=>{if(busy)return;const v=+b.dataset.i;flash(v);input.push(v);const pos=input.length-1;if(input[pos]!==seq[pos]){$('#simonInfo').textContent='Sequência incorreta. Recomeçando...';setTimeout(()=>{seq=[];round=0;next()},900);return}if(input.length===seq.length){busy=true;round++;if(round>=5){setTimeout(()=>complete('Você completou cinco sequências.'),500)}else setTimeout(next,700)}});function flash(i){btns[i].classList.add('lit');setTimeout(()=>btns[i].classList.remove('lit'),350)}async function play(){busy=true;$('#simonInfo').textContent='Observe...';for(const v of seq){await new Promise(r=>setTimeout(r,350));flash(v);await new Promise(r=>setTimeout(r,480))}input=[];busy=false;$('#simonInfo').textContent='Agora repita.'}function next(){seq.push(Math.floor(Math.random()*4));$('#simonInfo').textContent=`Rodada ${seq.length}/5`;setTimeout(play,600)}setTimeout(next,700)}
function mazeGame(){const map=[[0,0,1,0,0],[1,0,1,0,1],[0,0,0,0,1],[0,1,1,0,0],[0,0,0,1,0]],start=[0,0],goal=[4,4];let p=[...start];$('#gameArea').innerHTML='<div class="maze" id="maze"></div><div class="maze-controls"><button class="up">↑</button><button class="left">←</button><button class="down">↓</button><button class="right">→</button></div>';function draw(){const m=$('#maze');m.innerHTML='';for(let y=0;y<5;y++)for(let x=0;x<5;x++){const c=document.createElement('div');c.className='cell '+(map[y][x]?'wall':'');if(p[0]===y&&p[1]===x){c.classList.add('player');c.textContent='🧍'}else if(goal[0]===y&&goal[1]===x){c.classList.add('goal');c.textContent='🏆'}m.append(c)}}function move(dy,dx){const n=[p[0]+dy,p[1]+dx];if(n[0]<0||n[0]>4||n[1]<0||n[1]>4||map[n[0]][n[1]]){navigator.vibrate?.(35);return}p=n;draw();if(p[0]===goal[0]&&p[1]===goal[1])setTimeout(()=>complete('Você encontrou a saída do labirinto.'),400)}$('.up').onclick=()=>move(-1,0);$('.down').onclick=()=>move(1,0);$('.left').onclick=()=>move(0,-1);$('.right').onclick=()=>move(0,1);draw()}
function orderGame(){let expected=1,errors=0;const nums=shuffle([1,2,3,4,5,6,7,8,9]);const grid=document.createElement('div');grid.className='number-grid';nums.forEach(n=>{const b=document.createElement('button');b.className='number-btn';b.textContent=n;b.onclick=()=>{if(n===expected){b.classList.add('correct');expected++;if(expected===10)setTimeout(()=>complete(errors?'Você corrigiu o caminho e completou a ordem.':'Ordem perfeita, sem nenhum erro.'),450)}else{errors++;b.animate([{transform:'translateX(-6px)'},{transform:'translateX(6px)'},{transform:'translateX(0)'}],{duration:220});navigator.vibrate?.(40);$('#statusText').textContent=`O próximo número é ${expected}.`}};grid.append(b)});$('#gameArea').append(grid)}
function timingGame(){let state='waiting',start,timeout;$('#gameArea').innerHTML='<div class="timing-box" id="timingBox">Toque aqui para iniciar</div><div class="timing-result" id="timingResult"></div>';const box=$('#timingBox');box.onclick=()=>{if(state==='waiting'){state='armed';box.textContent='Espere ficar verde...';timeout=setTimeout(()=>{state='go';start=performance.now();box.classList.add('ready');box.textContent='TOQUE AGORA!'},1500+Math.random()*2500)}else if(state==='armed'){clearTimeout(timeout);state='waiting';box.classList.add('early');box.textContent='Muito cedo! Toque para tentar novamente.';setTimeout(()=>box.classList.remove('early'),500)}else if(state==='go'){const ms=Math.round(performance.now()-start);state='done';box.textContent='Reflexo registrado!';$('#timingResult').textContent=`${ms} ms`;setTimeout(()=>complete(`Seu tempo de reação foi de ${ms} milissegundos.`),900)}else{state='waiting';timingGame()}}}
async function typeLines(lines){const body=$('#terminalBody');body.innerHTML='';for(const line of lines){const p=document.createElement('div');p.className='cursor';body.append(p);for(const ch of line){p.textContent+=ch;await new Promise(r=>setTimeout(r,18+Math.random()*20))}p.classList.remove('cursor');await new Promise(r=>setTimeout(r,260))}}
async function runReward(){show('scannerScreen');const lines=['> iniciar scanner.exe','Carregando módulo de análise... OK','Validando conclusão dos jogos... 6/6','Recompensa especial encontrada.','Preparando Scanner de Qualidades...'];await typeLines(lines);$('#terminal').style.display='none';$('#scanCard').classList.remove('hidden');const qs=['Alegria','Bondade','Fé','Carisma','Inteligência','Simpatia','Humildade','Beleza','Delicadeza','Generosidade','Coragem','Sorriso bonito','Coração enorme','Criatividade','Paciência','Determinação','Gentileza','Autenticidade'];let pct=0,i=0;const timer=setInterval(()=>{pct=Math.min(100,pct+2);$('#scanProgress').style.width=pct+'%';$('#scanPercent').textContent=pct+'%';if(pct%6===0&&i<qs.length){const q=document.createElement('span');q.className='quality';q.textContent='✓ '+qs[i++];$('#qualities').append(q)}if(pct>=100){clearInterval(timer);setTimeout(()=>{show('finalScreen');confetti()},1000)}},55)}
function confetti(){const icons=['✨','⭐','💙','🌟','🎉'];for(let i=0;i<45;i++){const s=document.createElement('span');s.textContent=icons[Math.floor(Math.random()*icons.length)];s.style.left=Math.random()*100+'vw';s.style.animationDelay=Math.random()*1.6+'s';s.style.animationDuration=2.4+Math.random()*2+'s';$('#confetti').append(s)}}


// Compatibilidade de áudio para GitHub Pages e celulares
[musicA,musicB].forEach((audio)=>{
  audio.addEventListener('error',()=>{
    console.error('Falha ao carregar áudio:', audio.currentSrc || audio.src);
    statusText.textContent='O áudio não carregou. Confira se os arquivos MP3 estão na mesma pasta do index.html.';
  });
});
