const scenes=[...document.querySelectorAll('.scene')];let current=0;
const progressBar=document.querySelector('#progressBar'),progressText=document.querySelector('#progressText');
const musicOne=document.querySelector('#musicOne'),musicTwo=document.querySelector('#musicTwo');
const audioToggle=document.querySelector('#audioToggle'),volumeButton=document.querySelector('#volumeButton'),volumePanel=document.querySelector('#volumePanel'),volumeSlider=document.querySelector('#volumeSlider');
let audioStarted=false,muted=false,terminalDone=false,finalTyped=false;const baseVolume=.18;
musicOne.volume=baseVolume;musicTwo.volume=0;
function createStars(){const box=document.querySelector('#stars');for(let i=0;i<52;i++){const s=document.createElement('span');s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.setProperty('--speed',(2+Math.random()*5)+'s');s.style.animationDelay=(-Math.random()*5)+'s';box.appendChild(s)}}createStars();
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),1900)}
function updateProgress(){const n=Math.round((current/(scenes.length-1))*100);progressBar.style.width=n+'%';progressText.textContent=n+'%'}
function goTo(index){if(index<0||index>=scenes.length)return;const old=scenes[current];old.classList.add('exit');setTimeout(()=>{old.classList.remove('active','exit');current=index;scenes[current].classList.add('active');scenes[current].scrollTop=0;updateProgress();if(current===10){crossfade(musicOne,musicTwo,2200);typeFinal()}},350)}
document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>{if(b.hasAttribute('data-start-audio'))startAudio();goTo(current+1)}));
async function startAudio(){if(audioStarted)return;audioStarted=true;try{await musicOne.play();audioToggle.classList.add('active');audioToggle.textContent='♫'}catch(e){toast('Toque no ícone de música para iniciar.')}}
audioToggle.addEventListener('click',async()=>{if(!audioStarted){startAudio();return}muted=!muted;musicOne.muted=muted;musicTwo.muted=muted;audioToggle.textContent=muted?'♪':'♫';audioToggle.classList.toggle('active',!muted);toast(muted?'Música pausada':'Música ativada')});
volumeButton.addEventListener('click',()=>volumePanel.hidden=!volumePanel.hidden);
volumeSlider.addEventListener('input',e=>{const v=Number(e.target.value)/100;musicOne.volume=v;musicTwo.volume=v;muted=v===0;musicOne.muted=muted;musicTwo.muted=muted;audioToggle.textContent=muted?'♪':'♫'});
document.addEventListener('click',e=>{if(!volumePanel.hidden&&!volumePanel.contains(e.target)&&e.target!==volumeButton)volumePanel.hidden=true});
function crossfade(from,to,duration){if(!audioStarted)return;to.currentTime=0;to.volume=0;to.play().catch(()=>{});const target=Number(volumeSlider.value)/100,start=performance.now();function tick(now){const p=Math.min((now-start)/duration,1);from.volume=target*(1-p);to.volume=target*p;if(p<1)requestAnimationFrame(tick);else from.pause()}requestAnimationFrame(tick)}
function unlock(sel){const b=document.querySelector(sel);b.disabled=false;b.classList.remove('locked')}
const wait=ms=>new Promise(r=>setTimeout(r,ms));

// Vela
const candle=document.querySelector('#candle');candle.addEventListener('click',()=>{if(candle.classList.contains('lit'))return;candle.classList.add('lit');document.querySelector('#candleHint').textContent='A luz foi acesa. Agora, o próximo passo.';unlock('#candleNext');navigator.vibrate?.(35)});

// Contas do terço
const beadBox=document.querySelector('#rosaryBeads'),slotBox=document.querySelector('#rosarySlots');let beadsFound=0;
for(let i=0;i<5;i++){const slot=document.createElement('span');slotBox.appendChild(slot);const bead=document.createElement('button');bead.className='rosary-bead';bead.style.left=(8+Math.random()*80)+'%';bead.style.top=(10+Math.random()*68)+'%';bead.style.animationDelay=(-Math.random()*2)+'s';bead.setAttribute('aria-label','Conta luminosa');bead.addEventListener('click',()=>{if(bead.classList.contains('collected'))return;bead.classList.add('collected');slot.classList.add('filled');beadsFound++;document.querySelector('#rosaryStatus').textContent=beadsFound===5?'Caminho completo ✦':`${beadsFound} de 5 contas encontradas`;navigator.vibrate?.(18);if(beadsFound===5){unlock('#rosaryNext');toast('Muito bem, Linda.')}});beadBox.appendChild(bead)}

// Virtudes
let chosen=[];document.querySelectorAll('[data-virtue]').forEach(btn=>btn.addEventListener('click',()=>{const v=btn.dataset.virtue;if(btn.classList.contains('selected')){btn.classList.remove('selected');chosen=chosen.filter(x=>x!==v)}else if(chosen.length<3){btn.classList.add('selected');chosen.push(v);navigator.vibrate?.(20)}else toast('Escolha apenas três virtudes.');document.querySelector('#virtueResult').textContent=chosen.length===3?chosen.join(' • '):`${chosen.length} de 3 escolhidas`;if(chosen.length===3)unlock('#virtueNext');else{const b=document.querySelector('#virtueNext');b.disabled=true;b.classList.add('locked')}}));

// Palavra LINDA
let word='';const target='LINDA',display=document.querySelector('#wordDisplay');document.querySelectorAll('[data-letter]').forEach(btn=>btn.addEventListener('click',()=>{if(btn.disabled)return;word+=btn.dataset.letter;btn.disabled=true;btn.classList.add('used');display.textContent=word.padEnd(5,'_').split('').join(' ');navigator.vibrate?.(15);if(!target.startsWith(word)){toast('Quase! O sistema reiniciou as letras.');word='';setTimeout(()=>{display.textContent='_ _ _ _ _';document.querySelectorAll('[data-letter]').forEach(b=>{b.disabled=false;b.classList.remove('used')})},450)}else if(word===target){display.classList.add('solved');document.querySelector('#wordHint').textContent='Palavra reconhecida: LINDA. Sim, essa era fácil KKKKK.';unlock('#wordNext');toast('Acesso liberado, Linda.')}}));

// Estrelas
const constell=document.querySelector('#constellation');let found=0;for(let i=0;i<24;i++){const b=document.createElement('button');b.className='star-pick'+([5,13,21].includes(i)?' special':'');b.style.left=(6+Math.random()*88)+'%';b.style.top=(8+Math.random()*80)+'%';b.style.animationDelay=(-Math.random()*3)+'s';if(b.classList.contains('special'))b.addEventListener('click',()=>{if(b.classList.contains('found'))return;b.classList.add('found');found++;navigator.vibrate?.(25);if(found===3){document.querySelector('#verse').classList.add('show');unlock('#starNext');toast('Mensagem encontrada.')}});constell.appendChild(b)}

// Silêncio
let timerRunning=false;document.querySelector('#silenceBtn').addEventListener('click',()=>{if(timerRunning)return;timerRunning=true;const btn=document.querySelector('#silenceBtn'),timer=document.querySelector('#silenceTimer');btn.disabled=true;btn.style.opacity=.35;timer.classList.add('running');let n=10;timer.textContent=n;const id=setInterval(()=>{n--;timer.textContent=n>0?n:'✦';if(n<=0){clearInterval(id);timer.classList.remove('running');unlock('#silenceNext');toast('O silêncio também diz muita coisa.')}},1000)});

// Portas
const doorTexts={fé:'A fé não revela todo o caminho. Ela oferece luz suficiente para o próximo passo.',mistério:'Algumas respostas ficam mais bonitas quando chegam no tempo certo, princesa.',coragem:'Coragem não é ausência de medo. É continuar mesmo com o coração acelerado.'};
document.querySelectorAll('[data-door]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-door]').forEach(b=>b.classList.remove('open'));btn.classList.add('open');const box=document.querySelector('#doorMessage');box.textContent=doorTexts[btn.dataset.door];box.classList.add('show');unlock('#doorNext');navigator.vibrate?.(25)}));

// Jardim
const clues=['alguém especial','um pouco de suspense','muitas ideias católicas','e coragem em forma de código'];let flowerCount=0;const garden=document.querySelector('#flowerGarden');clues.forEach((clue,i)=>{const f=document.createElement('button');f.className='flower';f.innerHTML='<span>✿</span>';f.style.animationDelay=(-i*.45)+'s';f.addEventListener('click',()=>{if(f.classList.contains('picked'))return;f.classList.add('picked');flowerCount++;document.querySelector('#flowerMessage').textContent=clue;navigator.vibrate?.(18);if(flowerCount===clues.length){unlock('#flowerNext');setTimeout(()=>document.querySelector('#flowerMessage').textContent='As pistas apontam para alguém. Talvez você já tenha percebido…',500)}});garden.appendChild(f)});

// Terminal
const terminalLines=[
 {t:'> iniciando jornada_estendida...',c:'cmd',d:28},{t:'[OK] 9 capítulos concluídos',c:'ok',d:20},{t:'[OK] vela acesa',c:'ok',d:20},{t:'[OK] mistério montado',c:'ok',d:20},{t:`[OK] virtudes salvas: ${chosen.length?chosen.join(', '):'arquivo protegido'}`,c:'ok',d:18},{t:'> analisando palavra-chave...',c:'cmd',d:25},{t:'PALAVRA IDENTIFICADA: LINDA',c:'warn',d:28},{t:'> verificando nível de curiosidade...',c:'cmd',d:24},{t:'curiosidade: 97%',c:'warn',d:30},{t:'> carregando coragem... 18%',c:'warn',d:28},{t:'> carregando coragem... 47%',c:'warn',d:28},{t:'> carregando coragem... 81%',c:'warn',d:28},{t:'ERRO: medo de deixar tudo óbvio demais.',c:'error',d:22},{t:'> aplicando camada de suspense...',c:'cmd',d:27},{t:'[OK] indiretas protegidas',c:'ok',d:23},{t:'> tentando novamente...',c:'cmd',d:30},{t:'SUCESSO: arquivo final desbloqueado.',c:'ok',d:24}
];
async function typeLine(text,cls,speed){const term=document.querySelector('#terminal'),line=document.createElement('div');line.className=cls;term.appendChild(line);for(const ch of text){line.textContent+=ch;term.scrollTop=term.scrollHeight;await wait(speed)}const cursor=document.createElement('span');cursor.className='cursor';line.appendChild(cursor);await wait(190);cursor.remove()}
document.querySelector('#runTerminal').addEventListener('click',async e=>{if(terminalDone)return;terminalDone=true;e.target.disabled=true;e.target.textContent='SISTEMA EM EXECUÇÃO...';for(const l of terminalLines){await typeLine(l.t,l.c,l.d);await wait(85)}e.target.textContent='PROCESSO CONCLUÍDO';unlock('#terminalNext');navigator.vibrate?.([30,50,30])});

async function typeFinal(){if(finalTyped)return;finalTyped=true;const wrap=document.querySelector('#finalText');const paragraphs=['Sei que tudo isso pode parecer uma grande loucura.','Talvez você até pense que eu sou um pouco doido…','E, para falar a verdade, talvez eu seja mesmo. KKKKK','Mas, quando gosto de alguém, gosto de demonstrar de um jeito diferente.','Em vez de escrever apenas uma mensagem, resolvi criar uma pequena jornada.','Misturei um pouco da minha fé, das minhas “loucuras católicas”, do meu lado DEV e da minha paixão por programação.','Sempre gostei da ideia de transformar algumas linhas de código em algo capaz de transmitir sentimentos. Então pensei: por que não usar aquilo que gosto de aprender para criar uma experiência que pudesse arrancar um sorriso seu?','Porque essa foi a forma mais verdadeira que encontrei de mostrar um pedacinho de quem eu sou.','Cada detalhe, cada animação, cada fase, cada linha de código e cada reflexão foram pensados com muito carinho.','Espero, de coração, que você tenha gostado dessa pequena experiência. ❤️','Talvez você tenha percebido algumas indiretas durante o game… talvez não, Linda.','Mas sim: eu criei esta jornada pensando especialmente em você.','Não foi para fazer você perder muito tempo. Foi só uma forma diferente de te prender por alguns minutos de curiosidade, suspense e das minhas loucuras católicas misturadas com minhas habilidades de DEV. KKKKK','Cada fase, cada animação e cada código foram colocados aqui com carinho. Se você sorriu, ficou curiosa ou simplesmente chegou até o fim, então a missão já valeu a pena.','Obrigado por jogar até aqui, princesa.'];await wait(450);for(const text of paragraphs){const p=document.createElement('p');wrap.appendChild(p);for(const ch of text){p.textContent+=ch;await wait(17)}await wait(320)}}
document.querySelector('#restart').addEventListener('click',()=>location.reload());
document.addEventListener('visibilitychange',()=>{if(document.hidden){musicOne.pause();musicTwo.pause()}else if(audioStarted&&!muted){(current===10?musicTwo:musicOne).play().catch(()=>{})}});updateProgress();
